using HospitalManagement.API.Extensions.StartupExtensions;
using HospitalManagement.Persistence;
using NCase.Application;
using NCase.Application.Abstractions.Services.Common;
using NCase.Infrastructure;
using NCase.Infrastructure.Services;
using NCase.Infrastructure.Services.Storage.Local;

var builder = WebApplication.CreateBuilder(args);

builder.Services.AddControllers();
builder.Services.AddEndpointsApiExplorer();
builder.Services.AddSwaggerGen();

builder.Services.AddHttpContextAccessor();
builder.Services.AddApplicationServices();
builder.Services.AddInfrastructureServices(builder.Configuration);
builder.Services.AddStorage<LocalStorage>();
builder.Services.AddPersistenceServices();
builder.Services.HttpLoggingOptionsStartupExtension();
builder.Services.JsonOptionsStartupExtension();
builder.Services.AddEndpointsApiExplorer();
builder.Services.SwaggerOptionsExtension();
builder.Services.JwtOptionsStartupExtension(builder.Configuration);
builder.Services.AddScoped<IRickAndMortyApiService, RickAndMortyApiService>();


var app = builder.Build();
app.UseSwagger();
app.UseSwaggerUI(c =>
{
    c.SwaggerEndpoint("/swagger/NCase_V1/swagger.json", "NCase V1");
    c.RoutePrefix = string.Empty;
});

app.UseCors(x => x
          .AllowAnyOrigin()
          .AllowAnyMethod()
          .AllowAnyHeader());

app.UseAuthentication();
app.UseAuthorization();
app.UseHttpsRedirection();

app.MapControllers();

//using (var scoped = app.Services.CreateScope())
//{
//    var context = scoped.ServiceProvider.GetRequiredService<ApplicationDbContext>();

//    //System.Diagnostics.Process.Start(new System.Diagnostics.ProcessStartInfo
//    //{
//    //    FileName = "dotnet",
//    //    Arguments = "ef migrations add AutoGeneratedMigration",
//    //    RedirectStandardOutput = true,
//    //    RedirectStandardError = true,
//    //    UseShellExecute = false,
//    //    CreateNoWindow = true
//    //});

//    context.Database.Migrate();
//}

app.Run();
